# Handle the error so it doesn't halt execution.

try:
    print(n)
except:
    print("name error")